export const AppState = {
  layers: {
    "namria-boundary": {
      id: "layer-namria-boundary",
      name: "NAMRIA Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_NAMRIA_Boundary.geojson",
      style: {
        color: "#71bb5b",
        weight: 3,
        fillOpacity: 0,
      },
    },
    province: {
      id: "layer-province",
      name: "NAMRIA Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_NAMRIA_Provincial_Boundary.geojson",
      style: {
        color: "#e6c63c",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#e6c63c",
      },
    },
    municipality: {
      id: "layer-municipality",
      name: "NAMRIA Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_NAMRIA_Municipal_Boundary.geojson",
      style: {
        color: "#ce317f",
        weight: 1.2,
        dashArray: "4, 4",
        fillOpacity: 0,
      },
    },

    "cad-boundary": {
      id: "layer-cad-boundary",
      name: "CAD Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: true,
      url: "data/geojson/CAR_CAD_Boundary.geojson",
      style: {
        color: "#3b82f6",
        weight: 3,
        fillOpacity: 0,
      },
    },
    "cad-province": {
      id: "layer-cad-province",
      name: "CAD Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_CAD_Provincial_Boundary.geojson",
      style: {
        color: "#06b6d4",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#06b6d4",
      },
    },
    "cad-municipality": {
      id: "layer-cad-municipality",
      name: "CAD Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_CAD_Municipal_Boundary.geojson",
      style: {
        color: "#10b981",
        weight: 1.5,
        fillOpacity: 0.08,
        fillColor: "#10b981",
      },
    },
    climate: {
      id: "layer-climate",
      name: "CAR Climate",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_Climate.geojson",
      codeField: "CODE",
      style: {
        weight: 1.5,
        fillOpacity: 0.15,
      },
      codeColors: {
        "1st Type": "#D74042",
        "2nd Type": "#7C76D8",
        "3rd Type": "#E1E1E1",
        "4th Type": "#38C238",
      },
    },
    erosion: {
      id: "layer-erosion",
      name: "CAR Erosion",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_Erosion.geojson",
      codeField: "Erosion",
      style: {
        weight: 1.5,
        fillOpacity: 0.15,
      },
      codeColors: {
        "No Apparent Erosion": "#FFFFBF",
        "Slight Erosion": "#CFB667",
        "Moderate Erosion": "#A16A28",
        "Severe Erosion": "#732600",
        "Unclassified Erosion": "#E1E1E1",
        Reservoir: "#BFD9F2",
        River: "#FFFFFF",
      },
    },
    ngp: {
      id: "layer-ngp",
      name: "CAR NGP",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/ENGP_2011_2025.geojson",
      codeField: "YR_ESTAB",
      style: {
        weight: 1.5,
        fillOpacity: 0.15,
      },
      codeColors: {
        2011: "#FFFF00",
        2012: "#005CE6",
        2013: "#FF0000",
        2014: "#267300",
        2015: "#E69800",
        2016: "#C500FF",
        2017: "#19E802",
        2018: "#B5B35C",
        2020: "#A3E3ED",
        2021: "#FD7B33",
        2022: "#0225ED",
        2023: "#FF1493",
        2024: "#F5DEB3",
        2025: "#4B0082",
      },
    },
  },
  importedLayers: [],
  pendingLayerCount: 0,
};
