export const AppState = {
  layers: {
    // * NAMRIA
    "namria-boundary": {
      id: "layer-namria-boundary",
      name: "NAMRIA Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Boundary.geojson",
      style: {
        color: "#71bb5b",
        weight: 3,
        fillOpacity: 0,
      },
    },
    province: {
      id: "layer-province",
      name: "NAMRIA Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Provincial_Boundary.geojson",
      style: {
        color: "#e6c63c",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#e6c63c",
      },
    },
    municipality: {
      id: "layer-municipality",
      name: "NAMRIA Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Municipal_Boundary.geojson",
      style: {
        color: "#f7f442",
        weight: 1.2,
        dashArray: "4, 4",
        fillOpacity: 0,
      },
    },
    // * CADASTRE
    "cad-boundary": {
      id: "layer-cad-boundary",
      name: "CAD Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: true,
      url: "data/geojson/cadastre/CAR_CAD_Boundary.geojson",
      style: {
        color: "#3b82f6",
        weight: 3,
        fillOpacity: 0,
      },
    },
    "cad-province": {
      id: "layer-cad-province",
      name: "CAD Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_CAD_Provincial_Boundary.geojson",
      style: {
        color: "#06b6d4",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#06b6d4",
      },
    },
    "cad-municipality": {
      id: "layer-cad-municipality",
      name: "CAD Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_CAD_Municipal_Boundary.geojson",
      style: {
        color: "#10b981",
        weight: 1,
        fillOpacity: 0.08,
        fillColor: "#10b981",
      },
    },
    // * === Other Layers ===
    climate: {
      id: "layer-climate",
      name: "CAR Climate",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Climate.geojson",
      colorField: "CODE",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "1st Type": "#D74042",
        "2nd Type": "#7C76D8",
        "3rd Type": "#E1E1E1",
        "4th Type": "#38C238",
      },
    },
    ngp: {
      id: "layer-ngp",
      name: "CAR NGP",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/NGP_2011_2025.geojson",
      colorField: "YR_ESTAB",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        2011: "#FFFF00",
        2012: "#005CE6",
        2013: "#FF0000",
        2014: "#267300",
        2015: "#E69800",
        2016: "#C500FF",
        2017: "#19E802",
        2018: "#B5B35C",
        2020: "#A3E3ED",
        2021: "#FD7B33",
        2022: "#0225ED",
        2023: "#FF1493",
        2024: "#F5DEB3",
        2025: "#4B0082",
      },
    },
    slope: {
      id: "layer-slope",
      name: "CAR Slope",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Slope_Optimized.geojson",
      colorField: "SL_Cate",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "0 - 8": "#50A823",
        "8 - 18": "#8BD100",
        "18 - 30": "#FFFF00",
        "30 - 50": "#FF9A36",
        "Above 50": "#FF4A4A",
      },
    },
    erosion: {
      id: "layer-erosion",
      name: "CAR Erosion",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Erosion.geojson",
      colorField: "Erosion",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "No Apparent Erosion": "#FFFFBF",
        "Slight Erosion": "#CFB667",
        "Moderate Erosion": "#A16A28",
        "Severe Erosion": "#732600",
        "Unclassified Erosion": "#E1E1E1",
        Reservoir: "#BFD9F2",
        River: "#FFFFFF",
      },
    },
    annual_crop: {
      id: "layer-annual_crop",
      name: "CAR Annual Crop",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Annual_Crop_2025.geojson",
      style: {
        color: "#FEFAC2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FEFAC2",
      },
    },
    brush_shrubs: {
      id: "layer-brush_shrubs",
      name: "CAR Brush Shrubs",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Brush_Shrubs_2025.geojson",
      style: {
        color: "#FEFAC2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FEFAC2",
      },
    },
    built_up: {
      id: "layer-built_up",
      name: "CAR Built Up",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Built-Up_2025.geojson",
      style: {
        color: "#FF0000",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FF0000",
      },
    },
    closed_forest: {
      id: "layer-closed_forest",
      name: "CAR Closed Forest",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Closed_Forest_2025.geojson",
      style: {
        color: "#016300",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#016300",
      },
    },
    fishpond: {
      id: "layer-fishpond",
      name: "CAR Fishpond",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Fishpond_2025.geojson",
      style: {
        color: "#0081fe",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#0081fe",
      },
    },
    grassland: {
      id: "layer-grassland",
      name: "CAR Grassland",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Grassland_2025.geojson",
      style: {
        color: "#974749",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#974749",
      },
    },
    inland_water: {
      id: "layer-inland_water",
      name: "CAR Inland Water",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Inland_Water_2025.geojson",
      style: {
        color: "#281F94",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#281F94",
      },
    },
    // ! Mangrove Forest
    // ! Marshland/Swamp
    open_forest: {
      id: "layer-open_forest",
      name: "CAR Open Forest",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Open_Forest_2025.geojson",
      style: {
        color: "#02DB00",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#02DB00",
      },
    },
    open_barren: {
      id: "layer-open_barren",
      name: "CAR Open Barren",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Open_Barren_2025.geojson",
      style: {
        color: "#D2D2D2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#D2D2D2",
      },
    },
    perennial_crop_2025: {
      id: "layer-perennial_crop_2025",
      name: "CAR Perennial Crop 2025",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Perennial_Crop_2025.geojson",
      style: {
        color: "#e49a56",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#e49a56",
      },
    },
    geology: {
      id: "layer-geology",
      name: "CAR Geology",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Geology.geojson",
      style: {
        color: "#341ff0",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#341ff0",
      },
    },
    forestland: {
      id: "layer-forestland",
      name: "CAR Forestland",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Forestland.geojson",
      style: {
        color: "#4CE600",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#4CE600",
      },
    },
    a_and_d: {
      id: "layer-a_and_d",
      name: "CAR Ifugao LCM",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_A_and_D.geojson",
      style: {
        color: "#FF7F7F",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FF7F7F",
      },
    },
    flood_susceptibility: {
      id: "layer-flood_susceptibility",
      name: "CAR Flood Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Flood_Susceptibility.geojson",
      colorField: "FloodSusc",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        LF: "#E8BEFF",
        MF: "#C500FF",
        HF: "#673FD0",
        VHF: "#003893",
      },
    },
    fire_susceptibility: {
      id: "layer-fire_susceptibility",
      name: "CAR Fire Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Fire_Susceptibility.geojson",
      colorField: "Risk_Class",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        VL: "#267300",
        L: "#55FF00",
        M: "#FFFF00",
        H: "#FFAA00",
        VH: "#FF0000",
      },
    },
    landslide_susceptibility: {
      id: "layer-landslide_susceptibility",
      name: "CAR Landslide Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Landslide_Susceptibility.geojson",
      colorField: "LndslideSu",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        DB: "#B2B2B2",
        MDF: "#FFAA00",
        LL: "#4CE600",
        ML: "#FFFF00",
        HL: "#FF0000",
        VHL: "#732600",
      },
    },
  },
  importedLayers: [],
  pendingLayerCount: 0,
};
