export const AppState = {
  layers: {
    "namria-boundary": {
      id: "layer-namria-boundary",
      name: "NAMRIA Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: true,
      url: "data/geojson/CAR_NAMRIA_Boundary.geojson",
      style: {
        color: "#3b82f6",
        weight: 3,
        fillOpacity: 0,
      },
    },
    province: {
      id: "layer-province",
      name: "NAMRIA Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_NAMRIA_Provincial_Boundary.geojson",
      style: {
        color: "#06b6d4",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#06b6d4",
      },
    },
    municipality: {
      id: "layer-municipality",
      name: "NAMRIA Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_NAMRIA_Municipal_Boundary.geojson",
      style: {
        color: "#10b981",
        weight: 1.2,
        dashArray: "4, 4",
        fillOpacity: 0,
      },
    },

    "cad-boundary": {
      id: "layer-cad-boundary",
      name: "CAD Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_CAD_Boundary.geojson",
      style: {
        color: "#3b82f6",
        weight: 3,
        fillOpacity: 0,
      },
    },
    "cad-province": {
      id: "layer-cad-province",
      name: "CAD Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_CAD_Provincial_Boundary.geojson",
      style: {
        color: "#06b6d4",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#06b6d4",
      },
    },
    "cad-municipality": {
      id: "layer-cad-municipality",
      name: "CAD Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/CAR_CAD_Municipal_Boundary.geojson",
      style: {
        color: "#10b981",
        weight: 1.5,
        fillOpacity: 0.08,
        fillColor: "#10b981",
      },
    },
  },
  importedLayers: [],
  pendingLayerCount: 0,
};
